import { createClient, type SupabaseClient } from '@supabase/supabase-js';

// Revenue constants
const AD_RPM = 5.70; // $5.70 per 1000 pageviews (3 ads/page @ $1.90 CPM)
const REVENUE_PER_PAGEVIEW = AD_RPM / 1000; // $0.0057

// ROI multipliers per prize tier (in EUR)
const ROI_TIERS = [
  { max: 25, multiplier: 2 },   // €10-25 prizes → 2x ROI
  { max: 50, multiplier: 3 },   // €25-50 prizes → 3x ROI
  { max: Infinity, multiplier: 5 }, // €50+ prizes → 5x ROI
];

export function getRequiredRoi(prizeValueEur: number): number {
  for (const tier of ROI_TIERS) {
    if (prizeValueEur <= tier.max) return tier.multiplier;
  }
  return 5;
}

function getServiceClient(): SupabaseClient {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
  );
}

/**
 * Track ad revenue generated by a user's pageviews
 */
export async function trackAdRevenue(
  userId: string,
  pageviews: number,
  supabase?: SupabaseClient,
): Promise<void> {
  const client = supabase || getServiceClient();
  const revenue = pageviews * REVENUE_PER_PAGEVIEW;

  // Insert direct revenue
  await client.from('user_revenue_ledger').insert({
    user_id: userId,
    source: 'ad_revenue',
    amount_usd: revenue,
    description: `${pageviews} pageviews @ $${REVENUE_PER_PAGEVIEW.toFixed(4)}/PV`,
  });

  // Update user total revenue
  const { data: current } = await client.from('user_stats')
    .select('total_revenue_usd')
    .eq('user_id', userId)
    .single();

  if (current) {
    await client.from('user_stats')
      .update({ total_revenue_usd: (Number(current.total_revenue_usd) || 0) + revenue })
      .eq('user_id', userId);
  }

  // Propagate to referral chain
  await propagateReferralRevenue(userId, revenue, 'ad', client);
}

/**
 * Track affiliate CPA revenue
 */
export async function trackAffiliateRevenue(
  userId: string,
  cpaAmount: number,
  clickId: string,
  supabase?: SupabaseClient,
): Promise<void> {
  const client = supabase || getServiceClient();

  await client.from('user_revenue_ledger').insert({
    user_id: userId,
    source: 'affiliate_cpa',
    amount_usd: cpaAmount,
    reference_id: clickId,
    description: `Affiliate CPA conversion`,
  });

  // Update user total
  const { data } = await client
    .from('user_stats')
    .select('total_revenue_usd')
    .eq('user_id', userId)
    .single();

  if (data) {
    await client.from('user_stats')
      .update({ total_revenue_usd: (Number(data.total_revenue_usd) || 0) + cpaAmount })
      .eq('user_id', userId);
  }

  // Propagate to referral chain
  await propagateReferralRevenue(userId, cpaAmount, 'cpa', client);
}

/**
 * Propagate revenue credit to referral chain (10% L1, 5% L2)
 */
async function propagateReferralRevenue(
  userId: string,
  amountUsd: number,
  revenueType: 'ad' | 'cpa',
  client: SupabaseClient,
): Promise<void> {
  const { data: referrers } = await client
    .from('referral_tree')
    .select('referrer_id, level')
    .eq('user_id', userId)
    .in('level', [1, 2]);

  if (!referrers || referrers.length === 0) return;

  for (const ref of referrers) {
    const rate = ref.level === 1 ? 0.10 : 0.05;
    const credit = amountUsd * rate;
    if (credit < 0.0001) continue;

    const source = ref.level === 1
      ? (revenueType === 'ad' ? 'referral_ad_l1' : 'referral_cpa_l1')
      : (revenueType === 'ad' ? 'referral_ad_l2' : 'referral_cpa_l2');

    await client.from('user_revenue_ledger').insert({
      user_id: ref.referrer_id,
      source,
      amount_usd: credit,
      reference_id: userId,
      description: `L${ref.level} referral ${revenueType} revenue from user`,
    });

    // Update referrer total_revenue_usd
    const { data } = await client
      .from('user_stats')
      .select('total_revenue_usd')
      .eq('user_id', ref.referrer_id)
      .single();

    if (data) {
      await client.from('user_stats')
        .update({ total_revenue_usd: (Number(data.total_revenue_usd) || 0) + credit })
        .eq('user_id', ref.referrer_id);
    }
  }
}

/**
 * Get total revenue contribution for a user (direct + referral chain)
 */
export async function getUserTotalContribution(
  userId: string,
  supabase?: SupabaseClient,
): Promise<number> {
  const client = supabase || getServiceClient();

  const { data } = await client
    .from('user_revenue_ledger')
    .select('amount_usd')
    .eq('user_id', userId);

  if (!data) return 0;
  return data.reduce((sum, row) => sum + (Number(row.amount_usd) || 0), 0);
}

/**
 * Check if a user is eligible to redeem a prize (ROI guarantee)
 */
export async function checkRedemptionEligibility(
  userId: string,
  prizeValueEur: number,
  roiMultiplier?: number,
  supabase?: SupabaseClient,
): Promise<{ eligible: boolean; contribution: number; required: number }> {
  const multiplier = roiMultiplier ?? getRequiredRoi(prizeValueEur);
  const required = prizeValueEur * multiplier;
  const contribution = await getUserTotalContribution(userId, supabase);

  return {
    eligible: contribution >= required,
    contribution: Math.round(contribution * 100) / 100,
    required: Math.round(required * 100) / 100,
  };
}
